/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hci.da;

/**
 *
 * @author 429
 */
public class evolution extends javax.swing.JFrame {

    /**
     * Creates new form evolution
     */
    public evolution() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        close = new javax.swing.JButton();
        coin5 = new javax.swing.JButton();
        coin4 = new javax.swing.JButton();
        coin2 = new javax.swing.JButton();
        coin3 = new javax.swing.JButton();
        bt1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("วิวัฒนาการของเหรียญกาาปณ์ไทย");
        setBackground(new java.awt.Color(255, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        close.setBackground(new java.awt.Color(204, 204, 204));
        close.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        coin5.setBackground(new java.awt.Color(204, 255, 255));
        coin5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        coin5.setText("5.เงินเจียงและเงินธ็อก");
        coin5.setActionCommand("");
        coin5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        coin5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        coin5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coin5ActionPerformed(evt);
            }
        });

        coin4.setBackground(new java.awt.Color(204, 255, 255));
        coin4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        coin4.setText("4.เงินฮ้อยเเละเงินลาด");
        coin4.setActionCommand("");
        coin4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        coin4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        coin4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coin4ActionPerformed(evt);
            }
        });

        coin2.setBackground(new java.awt.Color(204, 255, 255));
        coin2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        coin2.setText("2.เงินตราสมัยอาณาจักรสุโขทัย");
        coin2.setActionCommand("");
        coin2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        coin2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        coin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coin2ActionPerformed(evt);
            }
        });

        coin3.setBackground(new java.awt.Color(204, 255, 255));
        coin3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        coin3.setText("3.เหรียญดีบุกเเละเงินอีเเปะ");
        coin3.setActionCommand("");
        coin3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        coin3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        coin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coin3ActionPerformed(evt);
            }
        });

        bt1.setBackground(new java.awt.Color(204, 255, 255));
        bt1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt1.setText("1.ก่อนจะเป็นพดด้วง");
        bt1.setActionCommand("");
        bt1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bt1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("วิวัฒนาการของเหรียญกษาปณ์ไทย");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(coin3)
                        .addGap(66, 66, 66)
                        .addComponent(coin4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bt1)
                                .addGap(64, 64, 64)
                                .addComponent(coin2))
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(close))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(coin5)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coin2)
                    .addComponent(bt1))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coin3)
                    .addComponent(coin4))
                .addGap(29, 29, 29)
                .addComponent(coin5)
                .addGap(32, 32, 32)
                .addComponent(close)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        // TODO add your handling code here:
        new coin1().setVisible(true);
        dispose();
    }//GEN-LAST:event_bt1ActionPerformed

    private void coin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coin2ActionPerformed
        // TODO add your handling code here:
        new coin2().setVisible(true);
        dispose();
    }//GEN-LAST:event_coin2ActionPerformed

    private void coin3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coin3ActionPerformed
        // TODO add your handling code here:
        new coin3().setVisible(true);
        dispose();
    }//GEN-LAST:event_coin3ActionPerformed

    private void coin4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coin4ActionPerformed
        // TODO add your handling code here:
        new coin4().setVisible(true);
        dispose();
    }//GEN-LAST:event_coin4ActionPerformed

    private void coin5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coin5ActionPerformed
        // TODO add your handling code here:
        new coin5().setVisible(true);
        dispose();
    }//GEN-LAST:event_coin5ActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        new Lobby().setVisible(true);
        dispose();
    }//GEN-LAST:event_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(evolution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(evolution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(evolution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(evolution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new evolution().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton close;
    private javax.swing.JButton coin2;
    private javax.swing.JButton coin3;
    private javax.swing.JButton coin4;
    private javax.swing.JButton coin5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
